### PR TITLE
Zslaszlo

### PR DESCRIPTION
**Pull request by zslaszlo**

### CODE REVIEW

**Comment by dziudek** [comment]
Hi @zslaszlo - it is work in progress? As I see the translations are incomplete.

**Comment by zslaszlo** [comment]
Hi!
Yes, as you see work is in progress. I just started to translate this great
CMS to hungarian. If you have some useful technical advice, or any
suggestion I will take it with many thanks.
Best regards:
Leslie


Tomasz Dziuda ***@***.***> ezt írta (időpont: 2023. febr.
26., Vas 10:02):

**Comment by dziudek** [comment]
@zslaszlo - as I see you work intensively on this translation - please let me know when it will be ready, so I will check it and merge :)

**Comment by zslaszlo** [comment]
Dear Tomasz,
After a lot of work, I think the translation is ready for testing. So
please check it and you can merge if everything OK. Of course I'm looking
forward to user feedback on possible improvements as well.
Have a great day!
Leslie

Tomasz Dziuda ***@***.***> ezt írta (időpont: 2023. márc. 8.,
Sze, 11:51):

**Pull request merged**
