### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by JoKeyser**
Please merge this initial German translation.

This PR targets version 0.40.2, which I tested it with. (Not sure about downward compatibility.)

Thanks to everyone who chipped in.
I think this initial version is a good start to keep translating - of course it may not be perfect yet, but I think it's quite useful already.
Of course anyone should feel welcome to improve this further.

@dziudek , in case you agree to merge - should I also provide the zip file, or do you want to add it? (In principle, it seems more secure to me if not anyone can upload any zip file for users...)

---

I've based this translation on the automatic translation provided [here](https://github.com/GetPublii/Publii/issues/628#issuecomment-1054712411), ~~and I am still in the process of improving it - but this takes time~~. This PR is to avoid duplication of work and allow collaboration, in case anyone wants to contribute - feel free to let me know your opinion here. I'll keep updating this description as I go along.

#### Things to check before merge

- [x] Decide/find consensus for translations of key concepts (see glossary below).
- [x] Check all translations in context of the App UI.
- [x] Check if URLs in the text have been mangled.

#### Current glossary en/de

Here are some phrases that I don't yet feel confident about. Lower entries are those that I need most help/time with.
Note that this list isn't complete, there probably still exist more urgent problems with the translation, especially with technical terms.

- "Excerpt"
    - Current translation: "Auszug"
    - Considered alternatives: "Ausschnitt"
- "Post"
    - Current translation: "Beitrag"
    - Considered alternatives: "Artikel"
- "Deployment"
    - Current translation: "Synchronisierung"
    - Considered alternatives: "Deployment", "Bereitstellung", "Veröffentlichung", ?
- "Thumbnail"
    - Current translation: "Vorschaubild"
    - Considered alternatives: "Miniaturansicht", "Bildvorschau"
- "Fallback"
    - Current translation: "Ausweichmöglichkeit"
    - Considered alternatives: "Notreserve", "Rückfallebene", "Rückfallwert", "alternativer Standardwert"
- "Tag" (in context of Publii's UI)
    - Current translation: "Schlagwort"
    - Considered alternatives: "Tag"
- "Tag" (as part of HTML)
    - Current translation: "Tag"
    - Considered alternatives: ?
- "Theme"
    - Current "translation": "Theme"
    - Considered alternatives: "Design", ?
- "Featured"
    - Current translation: "Hervorgehoben"
    - Considered alternatives: ?
- "Slug"
    - Current translation: "Slug"
    - Considered alternatives: ?
- "Pagination"
    - Current translation: "Paginierung"?
    - Considered alternatives: Seitennummerierung?

### CODE REVIEW

**Comment by ibes** [comment]
Awesome. 
Is it formal or informal?

Thanks for starting it. 
Thought about it a couple of times but as I don't use Publii and have other things that need my attention I never started. 

---

Wow "Deployment" in German is difficult. "Bereitstellung" feels like something a normal person (and as a developer) would not understand. 
What about "Veröffentlichen" - rather going for the result than the process?

"Pagination"/"Paginierung" - that is a really though one too. 

"Fallback" -> "Rückfallwert" - tricky. "Standardwert", "alternativer Standardwert"

**Comment by JoKeyser** [comment]
@ibes , thanks for checking in and sharing your thoughts, this is really helpful. I don't know either when exactly I'll have the time to finish it, I guess it will remain a collaborative effort anyhow.

I like your suggestion of "Veröffentlichen" for "Deployment", and will think about the others as well.

Currently, the language is formal ("Sie" instead of informal "Du"). I don't have a final opinion on this either.

**Comment by ibes** [comment]
I guess when formal is done it would be great to offer an informal version. 
German is strange and both forms have their importance.

**Comment by TimonStadelmann** [comment]
Hello guys,
I already started a German Version 2 weeks ago and I am translating it by hand.
I am currently working on it and only 200 lines in the translations.json file are missing.

**Comment by JoKeyser** [comment]
@TimonStadelmann , nice, that's good to know. Maybe its worth comparing/merging our efforts, and/or if yours is more mature, we could use that one as the starting point.

**Comment by JoKeyser** [comment]
@ibes , the translation "Veröffentlichung" for "deployment" doesn't work, as it clashes with the concept of "publishing a post" ("Beitrag veröffentlichen") which is used to organize a website in Publii, and thus certainly would lead to confusion.

I've also added a few improvements after checking the app's context.
I would say it's approaching a useful state - especially considering that not all strings are translatable yet, and language switching is still an experimental feature.
After a few more iterations, I'd prefer to merge this to get user feedback, rather than waiting for the perfect version before a merge.

@TimonStadelmann , you are probably also still working on your version? I'd be happy to find a good solution to merge both (or yield in favor of yours, if it's better or more consistent).

**Comment by Cameo007** [comment]
I would choose the following translations:

- Post -> Beitrag
- Thumbnail -> Miniaturansicht
- Tag -> Tag
- Theme -> Design
- Slug -> Slug (because the i didn't found a translation in the internet, only descriptions)
- Pagination -> "Seitennummerierung"?

**Comment by JoKeyser** [comment]
@Cameo007 thanks a lot for thinking along. (And sorry for my delayed response; I should soon have the time to think further and push this over the finish line.)

@Cameo007 , about "Miniaturansicht": I still prefer "Vorschaubild" since its shorter and more descriptive (but I may be wrong). Would you dislike "Vorschaubild", or is it just a smaller preference? I've tried to find out what the german-speaking community of Wordpress uses more, and it seems to be more in favor of "Vorschaubild", at least according to their forum at <https://de.wordpress.org/support/search/vorschaubild/> but of course, that's just one arbitraty example.

@Cameo007 , about translating "Theme" as "Design": I agree that "Design" would be a more fitting translation, but it's such a general term, while "Theme" has such a specific meaning that it would create more confusion, and be less searchable. People who want to change/download Themes will most likely have to deal with English pages, so it would be nice to match the word. Also, the German translation of Wordpress uses "Theme", see menu of <https://de.wordpress.org/>, so it seems well established.

@Cameo007 , about "Seitennummerierung": I'm still not entirely sure what the English term "Pagination" really refers to in Publii, I will have to figure this out. Is it just numbering pages, or is it also the process of splitting content into pages? In the latter case, it would be misleading to talk about just "numbering". It seems that the German word "Paginierung" refers only to numbering, whereas the English word "Pagination" refers to either numbering and/or splitting-into-pages, see <https://en.wikipedia.org/wiki/Pagination>.

**Review by rbenitezpagan — APPROVED** [review]
Thanks @JoKeyser

**Pull request merged**
